# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39c0387e3e7ccb41d2c4db33e2aed771a358730caf2022cc292d68396b472ce6ea6bbffeecd7253d481a326647eeff3e66aaf2ecc9f4fd81051bed697dbb84ba

test:
  secret_key_base: 479249de6a71038d6ff11f4b3bb2a86e4babb3f705f3407da74a65fb56ea5d16ad4c5902de3e5b6973cfe167dc516d3daf4b1bdfe5c3acb3e697f31a7e132047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
